### ISSUE TITLE
Erro quando não tem Extrato

### ISSUE THREAD

**Issue by GuidoBR** [henriquebastos/itauscraper#1]
Ao rodar o itauscrapper numa conta sem extrato (conta sem movimento), recebo essa mensagem de erro:

```
Traceback (most recent call last):
  File "/home/guido/.pyenv/versions/tools3/bin/itauscraper", line 11, in <module>
    load_entry_point('itauscraper==1.0', 'console_scripts', 'itauscraper')()
  File "/home/guido/.pyenv/versions/3.6.1/envs/tools3/lib/python3.6/site-packages/itauscraper/cli.py", line 43, in main
    data = itau.extrato()
  File "/home/guido/.pyenv/versions/3.6.1/envs/tools3/lib/python3.6/site-packages/itauscraper/scraper.py", line 60, in extrato
    url = page.url_max_period()
  File "/home/guido/.pyenv/versions/3.6.1/envs/tools3/lib/python3.6/site-packages/itauscraper/pages.py", line 73, in url_max_period
    href = nl[-1]
IndexError: list index out of range
```

**Comment by diegoponciano** [comment]
Minha conta tem movimento, e dá o mesmo erro. Vou tentar descobrir mais alguma coisa.

**Comment by esbap** [comment]
Estou com o mesmo problema, minha conta tem movimento e é Personnalite. Acessando a página direto do navegador, percebi que não tem uma opção extrato no menu. Será que não é isso?

**Comment by tuler** [comment]
#6

**Comment by henriquebastos** [comment]
Isso não funciona mais. Tô começando a rascunhar uma alternativa em #8.
