### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by ccrvlh** [henriquebastos/itauscraper#9]
```
Traceback (most recent call last):
  File "itau.py", line 162, in <module>
    itau.login('agencia', 'conta', 'nome', 'senha')
  File "itau.py", line 112, in login
    titular = self.driver.wait_until(present(link_contains(nome)))
  File "itau.py", line 31, in wait_until
    return WebDriverWait(self, timeout, interval).until(method)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

**Comment by ccrvlh** [comment]
Funcionando após:

1. Alterar método de espera:
`        return self.wait_until(EC.presence_of_element_located((By.ID, "teclas clearfix")))`

2. Excluir dependência de selecionar titular:
No meu caso, sou o único titular, e como ele não achava meu nome para selecionar dava TimeOut...
